export const ICON_LABELS: Record<string, string> = {
  home: "Casa",
  search: "Pesquisar",
  settings: "Definições",
  user: "Utilizador",
  users: "Utilizadores",
  bell: "Notificação",
  mail: "Email",
  chat: "Conversa",
  phone: "Telefone",
  heart: "Coração",
  star: "Estrela",
  flag: "Bandeira",
  bookmark: "Marcador",
  lock: "Bloquear",
  unlock: "Desbloquear",
  shield: "Proteção",
  check: "Confirmar",
  close: "Fechar",
  plus: "Adicionar",
  minus: "Remover",
  edit: "Editar",
  trash: "Eliminar",
  download: "Descarregar",
  upload: "Carregar",
  refresh: "Atualizar",
  share: "Partilhar",
  link: "Ligação",
  copy: "Copiar",
  play: "Reproduzir",
  pause: "Pausar",
  stop: "Parar",
  image: "Imagem",
  camera: "Câmara",
  video: "Vídeo",
  volume: "Volume",
  music: "Música",
  cart: "Carrinho",
  tag: "Etiqueta",
  "credit-card": "Cartão",
  dollar: "Dinheiro",
  percent: "Percentagem",
  chart: "Gráfico",
  folder: "Pasta",
  file: "Ficheiro",
  clock: "Relógio",
  calendar: "Calendário",
  sun: "Sol",
  moon: "Lua",
  wifi: "Wifi",
  cloud: "Nuvem",
  "map-pin": "Localização",
  eye: "Ver",
  filter: "Filtrar",
  grid: "Grelha",
  list: "Lista",
  menu: "Menu",
  "arrow-up": "Seta para cima",
  "arrow-down": "Seta para baixo",
  "arrow-left": "Seta para a esquerda",
  "arrow-right": "Seta para a direita",
  info: "Informação",
  warning: "Aviso",
};

export function labelOf(iconName: string): string {
  return ICON_LABELS[iconName] ?? iconName;
}
