export const CATEGORIES: Record<string, string[]> = {
  "Diversos": ["activity","alert-circle","alert-triangle","angry","annoyed","at-sign","atom","award","backpack","bird","braces","brackets","brush","building","building-2","calculator","cat","circle-alert","circle-dot","circle-help","component","corner-up-right","crop","crown","diamond","divide","dna","dog","door-open","equal","factory","fish","flag","flask-conical","frown","gauge","gavel","gem","globe","globe-2","graduation-cap","hammer","handshake","hash","heart","heart-handshake","help-circle","home","hourglass","house","info","lamp","landmark","laugh","layers","layers-2","lightbulb","magnet","medal","meh","more-horizontal","more-vertical","orbit","palette","paw-print","pen-tool","pipette","puzzle","rabbit","recycle","ruler","satellite","scale","school","scissors","settings","settings-2","shapes","sigma","smile","sparkles","square","square-pen","star","star-half","target","telescope","test-tube","thumbs-down","thumbs-up","ticket","timer","triangle","trophy","turtle","wand","wand-2","watch","wrench","zap","zap-off"],
  "Organização": ["alarm-clock","archive","book","book-open","bookmark","briefcase","calendar","calendar-days","clock","clock-3","file","file-code","file-json","files","folder","folder-open"],
  "Interface": ["align-center","align-justify","align-left","arrow-down","arrow-down-left","arrow-left","arrow-right","arrow-up","arrow-up-right","chevron-down","chevron-left","chevron-right","chevron-up","chevrons-up-down","columns","eye","eye-closed","eye-off","filter","grid","grid-3x3","kanban","layout","layout-dashboard","layout-grid","list","list-checks","list-ordered","list-tree","menu","rows","search","sliders","sliders-horizontal","sliders-vertical","table","table-2","tablet","toggle-left","toggle-right","user","user-check","user-minus","user-plus","user-round","user-x","users","users-round"],
  "Transporte": ["anchor","bike","bus","car","car-front","compass","map","map-pin","navigation","plane","plane-takeoff","rocket","ship","truck"],
  "Multimédia": ["aperture","bug-play","camera","camera-off","clapperboard","film","image","mic","mic-off","microscope","music","music-2","pause","play","radio","stop-circle","tv","video","video-off","volume","volume-1","volume-2"],
  "Ações": ["badge-check","bookmark-check","bookmark-plus","box","calendar-check","calendar-plus","check","check-check","check-square","circle-check","circle-minus","circle-plus","circle-x","clipboard","clipboard-check","copy","credit-card","download","edit","edit-2","edit-3","file-minus","file-plus","file-text","folder-plus","hexagon","image-plus","inbox","link","link-2","minus","pencil","pencil-ruler","plus","refresh-ccw","refresh-cw","rotate-cw","save","share","share-2","shield-check","shield-plus","square-check","trash","trash-2","upload","volume-x","x"],
  "Comércio": ["badge-percent","banknote","bar-chart","bar-chart-2","coins","diamond-percent","dollar-sign","euro","gift","line-chart","octagon","package","percent","pie-chart","piggy-bank","receipt","shopping-bag","shopping-cart","store","tag","tags","trending-down","trending-up","wallet","warehouse"],
  "Tecnologia": ["barcode","battery","battery-charging","battery-low","binary","bluetooth","bug","code","code-2","cpu","database","gamepad-2","git-branch","git-merge","git-pull-request","hard-drive","joystick","keyboard","laptop","monitor","mouse","plug","power","power-off","printer","qr-code","server","signal","square-terminal","terminal","wifi","wifi-off"],
  "Comunicação": ["bell","bell-off","bell-ring","contact","headphones","id-card","mail","mail-open","message-circle","message-square","phone","phone-call","phone-off","send","send-horizontal","smartphone"],
  "Segurança": ["blocks","fingerprint","key","key-round","lock","lock-keyhole","scan","shield","shield-alert","unlock","unlock-keyhole"],
  "Natureza": ["cloud","cloud-lightning","cloud-rain","cloud-snow","cloudy","droplet","droplets","flame","flower","flower-2","leaf","moon","moon-star","mountain","mountain-snow","palmtree","rainbow","snowflake","sprout","sun","sun-dim","sun-medium","sunrise","sunset","thermometer","tornado","train","tree-pine","trees","umbrella","waves","wind"],
};

export function categoryOf(iconName: string): string {
  for (const [category, names] of Object.entries(CATEGORIES)) {
    if (names.includes(iconName)) return category;
  }
  return "Diversos";
}
