export const ICON_LABELS: Record<string, string> = {
  "activity": "Atividade",
  "alarm-clock": "Alarme relógio",
  "alert-circle": "Alerta círculo",
  "alert-triangle": "Alerta triângulo",
  "align-center": "Alinhar centro",
  "align-justify": "Alinhar justificar",
  "align-left": "Alinhar esquerda",
  "anchor": "Âncora",
  "angry": "Zangado",
  "annoyed": "Incomodado",
  "aperture": "Abertura",
  "archive": "Arquivo",
  "arrow-down": "Seta baixo",
  "arrow-down-left": "Seta baixo esquerda",
  "arrow-left": "Seta esquerda",
  "arrow-right": "Seta direita",
  "arrow-up": "Seta cima",
  "arrow-up-right": "Seta cima direita",
  "at-sign": "Arroba sinal",
  "atom": "Átomo",
  "award": "Prémio",
  "backpack": "Mochila",
  "badge-check": "Distintivo confirmar",
  "badge-percent": "Distintivo percentagem",
  "banknote": "Nota",
  "bar-chart": "Barras gráfico",
  "bar-chart-2": "Barras gráfico 2",
  "barcode": "Código de barras",
  "battery": "Bateria",
  "battery-charging": "Bateria a carregar",
  "battery-low": "Bateria baixo",
  "bell": "Sino",
  "bell-off": "Sino desligado",
  "bell-ring": "Sino anel",
  "bike": "Bicicleta",
  "binary": "Binário",
  "bird": "Pássaro",
  "blocks": "Blocos",
  "bluetooth": "Bluetooth",
  "book": "Livro",
  "book-open": "Livro aberto",
  "bookmark": "Marcador",
  "bookmark-check": "Marcador confirmar",
  "bookmark-plus": "Marcador adicionar",
  "box": "Caixa",
  "braces": "Chavetas",
  "brackets": "Parênteses",
  "briefcase": "Pasta",
  "brush": "Pincel",
  "bug": "Erro",
  "bug-play": "Erro reproduzir",
  "building": "Edifício",
  "building-2": "Edifício 2",
  "bus": "Autocarro",
  "calculator": "Calculadora",
  "calendar": "Calendário",
  "calendar-check": "Calendário confirmar",
  "calendar-days": "Calendário dias",
  "calendar-plus": "Calendário adicionar",
  "camera": "Câmara",
  "camera-off": "Câmara desligado",
  "car": "Carro",
  "car-front": "Carro frente",
  "cat": "Gato",
  "check": "Confirmar",
  "check-check": "Confirmar confirmar",
  "check-square": "Confirmar quadrado",
  "chevron-down": "Seta baixo",
  "chevron-left": "Seta esquerda",
  "chevron-right": "Seta direita",
  "chevron-up": "Seta cima",
  "chevrons-up-down": "Setas cima baixo",
  "circle-alert": "Círculo alerta",
  "circle-check": "Círculo confirmar",
  "circle-dot": "Círculo ponto",
  "circle-help": "Círculo ajuda",
  "circle-minus": "Círculo remover",
  "circle-plus": "Círculo adicionar",
  "circle-x": "Círculo fechar",
  "clapperboard": "Claquete",
  "clipboard": "Área de transferência",
  "clipboard-check": "Área de transferência confirmar",
  "clock": "Relógio",
  "clock-3": "Relógio 3",
  "cloud": "Nuvem",
  "cloud-lightning": "Nuvem relâmpago",
  "cloud-rain": "Nuvem chuva",
  "cloud-snow": "Nuvem neve",
  "cloudy": "Nublado",
  "code": "Código",
  "code-2": "Código 2",
  "coins": "Moedas",
  "columns": "Colunas",
  "compass": "Bússola",
  "component": "Componente",
  "contact": "Contacto",
  "copy": "Copiar",
  "corner-up-right": "Canto cima direita",
  "cpu": "Processador",
  "credit-card": "Crédito cartão",
  "crop": "Recortar",
  "crown": "Coroa",
  "database": "Base de dados",
  "diamond": "Diamante",
  "diamond-percent": "Diamante percentagem",
  "divide": "Dividir",
  "dna": "Adn",
  "dog": "Cão",
  "dollar-sign": "Dólar sinal",
  "door-open": "Porta aberto",
  "download": "Descarregar",
  "droplet": "Gota",
  "droplets": "Gotas",
  "edit": "Editar",
  "edit-2": "Editar 2",
  "edit-3": "Editar 3",
  "equal": "Igual",
  "euro": "Euro",
  "eye": "Olho",
  "eye-closed": "Olho fechado",
  "eye-off": "Olho desligado",
  "factory": "Fábrica",
  "file": "Ficheiro",
  "file-code": "Ficheiro código",
  "file-json": "Ficheiro json",
  "file-minus": "Ficheiro remover",
  "file-plus": "Ficheiro adicionar",
  "file-text": "Ficheiro texto",
  "files": "Ficheiros",
  "film": "Filme",
  "filter": "Filtro",
  "fingerprint": "Impressão digital",
  "fish": "Peixe",
  "flag": "Bandeira",
  "flame": "Chama",
  "flask-conical": "Frasco cónico",
  "flower": "Flor",
  "flower-2": "Flor 2",
  "folder": "Pasta",
  "folder-open": "Pasta aberto",
  "folder-plus": "Pasta adicionar",
  "frown": "Triste",
  "gamepad-2": "Comando 2",
  "gauge": "Medidor",
  "gavel": "Martelo",
  "gem": "Gema",
  "gift": "Presente",
  "git-branch": "Git ramo",
  "git-merge": "Git fundir",
  "git-pull-request": "Git puxar pedido",
  "globe": "Globo",
  "globe-2": "Globo 2",
  "graduation-cap": "Graduação boné",
  "grid": "Grelha",
  "grid-3x3": "Grelha 3x3",
  "hammer": "Martelo",
  "handshake": "Aperto de mão",
  "hard-drive": "Rígido disco",
  "hash": "Cardinal",
  "headphones": "Auscultadores",
  "heart": "Coração",
  "heart-handshake": "Coração aperto de mão",
  "help-circle": "Ajuda círculo",
  "hexagon": "Hexágono",
  "home": "Casa",
  "hourglass": "Ampulheta",
  "house": "Casa",
  "id-card": "Identificação cartão",
  "image": "Imagem",
  "image-plus": "Imagem adicionar",
  "inbox": "Caixa de entrada",
  "info": "Informação",
  "joystick": "Joystick",
  "kanban": "Kanban",
  "key": "Chave",
  "key-round": "Chave redondo",
  "keyboard": "Teclado",
  "lamp": "Candeeiro",
  "landmark": "Monumento",
  "laptop": "Portátil",
  "laugh": "Rir",
  "layers": "Camadas",
  "layers-2": "Camadas 2",
  "layout": "Esquema",
  "layout-dashboard": "Esquema painel",
  "layout-grid": "Esquema grelha",
  "leaf": "Folha",
  "lightbulb": "Lâmpada",
  "line-chart": "Linha gráfico",
  "link": "Ligação",
  "link-2": "Ligação 2",
  "list": "Lista",
  "list-checks": "Lista confirmações",
  "list-ordered": "Lista ordenada",
  "list-tree": "Lista árvore",
  "lock": "Bloquear",
  "lock-keyhole": "Bloquear fechadura",
  "magnet": "Íman",
  "mail": "Email",
  "mail-open": "Email aberto",
  "map": "Mapa",
  "map-pin": "Mapa marcador",
  "medal": "Medalha",
  "meh": "Indiferente",
  "menu": "Menu",
  "message-circle": "Mensagem círculo",
  "message-square": "Mensagem quadrado",
  "mic": "Microfone",
  "mic-off": "Microfone desligado",
  "microscope": "Microscópio",
  "minus": "Remover",
  "monitor": "Monitor",
  "moon": "Lua",
  "moon-star": "Lua estrela",
  "more-horizontal": "Mais horizontal",
  "more-vertical": "Mais vertical",
  "mountain": "Montanha",
  "mountain-snow": "Montanha neve",
  "mouse": "Rato",
  "music": "Música",
  "music-2": "Música 2",
  "navigation": "Navegação",
  "octagon": "Octógono",
  "orbit": "Órbita",
  "package": "Pacote",
  "palette": "Paleta",
  "palmtree": "Palmeira",
  "pause": "Pausar",
  "paw-print": "Pata imprimir",
  "pen-tool": "Caneta ferramenta",
  "pencil": "Lápis",
  "pencil-ruler": "Lápis régua",
  "percent": "Percentagem",
  "phone": "Telefone",
  "phone-call": "Telefone chamada",
  "phone-off": "Telefone desligado",
  "pie-chart": "Circular gráfico",
  "piggy-bank": "Mealheiro banco",
  "pipette": "Pipeta",
  "plane": "Avião",
  "plane-takeoff": "Avião descolagem",
  "play": "Reproduzir",
  "plug": "Ficha",
  "plus": "Adicionar",
  "power": "Energia",
  "power-off": "Energia desligado",
  "printer": "Impressora",
  "puzzle": "Puzzle",
  "qr-code": "Qr código",
  "rabbit": "Coelho",
  "radio": "Rádio",
  "rainbow": "Arco-íris",
  "receipt": "Recibo",
  "recycle": "Reciclar",
  "refresh-ccw": "Atualizar anti-horário",
  "refresh-cw": "Atualizar horário",
  "rocket": "Foguetão",
  "rotate-cw": "Rodar horário",
  "rows": "Linhas",
  "ruler": "Régua",
  "satellite": "Satélite",
  "save": "Guardar",
  "scale": "Balança",
  "scan": "Digitalizar",
  "school": "Escola",
  "scissors": "Tesoura",
  "search": "Pesquisar",
  "send": "Enviar",
  "send-horizontal": "Enviar horizontal",
  "server": "Servidor",
  "settings": "Definições",
  "settings-2": "Definições 2",
  "shapes": "Formas",
  "share": "Partilhar",
  "share-2": "Partilhar 2",
  "shield": "Proteção",
  "shield-alert": "Proteção alerta",
  "shield-check": "Proteção confirmar",
  "shield-plus": "Proteção adicionar",
  "ship": "Navio",
  "shopping-bag": "Compras saco",
  "shopping-cart": "Compras carrinho",
  "sigma": "Sigma",
  "signal": "Sinal",
  "sliders": "Controlos",
  "sliders-horizontal": "Controlos horizontal",
  "sliders-vertical": "Controlos vertical",
  "smartphone": "Smartphone",
  "smile": "Sorriso",
  "snowflake": "Floco de neve",
  "sparkles": "Brilhos",
  "sprout": "Rebento",
  "square": "Quadrado",
  "square-check": "Quadrado confirmar",
  "square-pen": "Quadrado caneta",
  "square-terminal": "Quadrado terminal",
  "star": "Estrela",
  "star-half": "Estrela meio",
  "stop-circle": "Parar círculo",
  "store": "Loja",
  "sun": "Sol",
  "sun-dim": "Sol fraco",
  "sun-medium": "Sol médio",
  "sunrise": "Nascer do sol",
  "sunset": "Pôr do sol",
  "table": "Tabela",
  "table-2": "Tabela 2",
  "tablet": "Tablet",
  "tag": "Etiqueta",
  "tags": "Etiquetas",
  "target": "Alvo",
  "telescope": "Telescópio",
  "terminal": "Terminal",
  "test-tube": "Teste tubo",
  "thermometer": "Termómetro",
  "thumbs-down": "Polegar baixo",
  "thumbs-up": "Polegar cima",
  "ticket": "Bilhete",
  "timer": "Temporizador",
  "toggle-left": "Alternar esquerda",
  "toggle-right": "Alternar direita",
  "tornado": "Tornado",
  "train": "Comboio",
  "trash": "Eliminar",
  "trash-2": "Eliminar 2",
  "tree-pine": "Árvore pinheiro",
  "trees": "Árvores",
  "trending-down": "Tendência baixo",
  "trending-up": "Tendência cima",
  "triangle": "Triângulo",
  "trophy": "Troféu",
  "truck": "Camião",
  "turtle": "Tartaruga",
  "tv": "Televisão",
  "umbrella": "Guarda-chuva",
  "unlock": "Desbloquear",
  "unlock-keyhole": "Desbloquear fechadura",
  "upload": "Carregar",
  "user": "Utilizador",
  "user-check": "Utilizador confirmar",
  "user-minus": "Utilizador remover",
  "user-plus": "Utilizador adicionar",
  "user-round": "Utilizador redondo",
  "user-x": "Utilizador fechar",
  "users": "Utilizadores",
  "users-round": "Utilizadores redondo",
  "video": "Vídeo",
  "video-off": "Vídeo desligado",
  "volume": "Volume",
  "volume-1": "Volume 1",
  "volume-2": "Volume 2",
  "volume-x": "Volume fechar",
  "wallet": "Carteira",
  "wand": "Varinha",
  "wand-2": "Varinha 2",
  "warehouse": "Armazém",
  "watch": "Relógio",
  "waves": "Ondas",
  "wifi": "Wifi",
  "wifi-off": "Wifi desligado",
  "wind": "Vento",
  "wrench": "Chave inglesa",
  "x": "Fechar",
  "zap": "Raio",
  "zap-off": "Raio desligado",
};

export function labelOf(iconName: string): string {
  return ICON_LABELS[iconName] ?? iconName;
}
